server:
  port: 0
  
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    
spring:
  application:
    name: PRODUCT-SERVICE
  cloud:
    config:
      enabled: true        
