spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Products?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: NkweMapoulo@1
    username: root
  jpa:
    hibernate:
      ddl-auto: update        
  application:
    name: ONLINESHOPPING-PRODUCT-SERVICE 
